spring:
  profiles:
    active: "dev"
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:33060/java-meedu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
    username: "root"
    password: "root"
  # Redis配置
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password:
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
          max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
          max-idle: 20    # 连接池中的最大空闲连接(默认8)
          min-idle: 5     # 连接池中的最小空闲连接(默认0)

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

playedu:
  captcha:
    expire: 300 #分5钟
    cache-prefix: "captcha:key:"

